// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web desteği şimdilik yok.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: 'AIzaSyBT6SGfx3yFe6PBgN9nsJPv8OV6qsSt7K4',
          appId: '1:787725089561:android:e51b8d3d494846026d2388',
          messagingSenderId: '787725089561',
          projectId: 'travel-asistant-fb7c6',
          storageBucket: 'travel-asistant-fb7c6.firebasestorage.app',
        );
      default:
        throw UnsupportedError('Bu platform için Firebase desteği yok.');
    }
  }
}
